#!/bin/bash
# Install direct wgtunnel commands system-wide.
# Creates /usr/local/bin/wgtunnel-* wrappers pointing at this repo.
set -e
cd "$(dirname "$0")"
[ -x ./wgtunnel ] || ./build.sh
for cmd in proxy rotate status list test export import dns stop restart boot; do
  cat > "/usr/local/bin/wgtunnel-$cmd" <<EOF
#!/bin/sh
# auto-generated by wgtunnel/install.sh
exec /root/wgtunnel/wgtunnel $cmd "\$@"
EOF
  chmod +x "/usr/local/bin/wgtunnel-$cmd"
  echo "installed wgtunnel-$cmd"
done
echo "✅ done. Try: wgtunnel-status"
